const A=document.getElementById('app'),D=STUDY_DATA,S={c:null,b:null,s:null,sub:null,ch:null,t:null,tab:'learn',used:0};
const esc=x=>String(x).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function home(){Object.assign(S,{c:null,b:null,s:null,sub:null,ch:null,t:null,tab:'learn'});render()}
function box(x){A.innerHTML='<div class="wrap">'+x+'</div>';scrollTo(0,0)}
function render(){if(!S.c)return homePage();if(!S.b)return boards();if(!S.s)return streams();if(!S.sub)return subjects();if(!S.ch)return chapters();if(!S.t)return topics();topic()}
function homePage(){box(`<section class="hero"><div class="eyebrow">FREE • STUDENT-FIRST • INDIA</div><h1>Learn.<br>Practice.<br>Understand.</h1><p class="lead">A free study platform for learning concepts, practicing questions, solving problems and getting help.</p><div class="box"><b>WHAT ARE YOU STUDYING?</b><div class="grid" style="margin-top:16px">${Object.keys(D.classes).map(c=>`<button class="choice" onclick="S.c='${c}';render()"><strong>Class ${c}</strong><small>Open curriculum</small></button>`).join('')}</div></div></section><div class="grid"><div class="content"><h3>📚 Learn</h3><span class="muted">Explanations, examples and key points.</span></div><div class="content"><h3>🧠 Practice</h3><span class="muted">Questions that build understanding.</span></div><div class="content"><h3>🧮 Solve</h3><span class="muted">Learning-focused calculators.</span></div><div class="content"><h3>🤖 Ask AI</h3><span class="muted">Personalized tutoring when you are stuck.</span></div></div>`)}
function nav(title,items,fn){box(`<div class="crumb"><button onclick="home()">Home</button> / ${esc(title)}</div><section class="hero"><div class="eyebrow">CHOOSE</div><h2>${esc(title)}</h2><div class="grid">${items.map(x=>`<button class="choice" onclick="${fn}('${esc(x)}');render()"><strong>${esc(x)}</strong><small>Continue</small></button>`).join('')}</div></section>`)}
function boards(){nav('Board',Object.keys(D.classes[S.c].boards),x=>S.b=x)}
function streams(){nav('Stream',Object.keys(D.classes[S.c].boards[S.b].streams),x=>S.s=x)}
function subjects(){nav('Subject',Object.keys(stream().subjects),x=>S.sub=x)}
function chapters(){nav('Chapter',Object.keys(subject().chapters),x=>S.ch=x)}
function topics(){nav('Topic',Object.keys(chapter().topics),x=>S.t=x)}
function stream(){return D.classes[S.c].boards[S.b].streams[S.s]}function subject(){return stream().subjects[S.sub]}function chapter(){return subject().chapters[S.ch]}function T(){return chapter().topics[S.t]}
function topic(){let t=T(),body='';if(S.tab==='learn')body=`<div class="content"><h3>Explanation</h3><p>${esc(t.explanation)}</p></div><div class="content"><h3>Example</h3>${t.examples.map(x=>`<p>${esc(x)}</p>`).join('')}</div><div class="content"><h3>Key points</h3><ul>${t.keyPoints.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`;if(S.tab==='practice'||S.tab==='quiz')body=t.questions.map((q,i)=>`<div class="question"><b>${S.tab==='quiz'?'Quick Quiz':'Practice '+(i+1)}</b><p>${esc(q.text)}</p><div class="opts">${q.options.map((o,j)=>`<button onclick="answer(${i},${j},this)">${esc(o)}</button>`).join('')}</div><div id="f${i}"></div></div>`).join('');if(S.tab==='formulas')body=`<div class="content"><h3>Formula sheet</h3>${t.formulas.map(x=>`<div class="formula">${esc(x)}</div>`).join('')}</div>`;if(S.tab==='solve')body=`<div class="content"><h3>Linear equation solver</h3><p class="muted">Solve ax + b = c.</p><input id="aa" type="number" placeholder="a"><input id="bb" type="number" placeholder="b"><input id="cc" type="number" placeholder="c"><button class="primary" onclick="solve()">SOLVE</button><div id="sr"></div></div>`;if(S.tab==='ai')body=`<div class="content ai"><h3>🤖 AI TUTOR</h3><p><b>${3-S.used} questions remaining today</b></p><p class="muted">The secure AI backend is intentionally not connected in V1. This screen is ready for the authentication + AI phase.</p><textarea id="aq" rows="5" placeholder="Ask a question about this topic..."></textarea><button class="primary" onclick="ask()">ASK AI</button><div id="ar"></div></div>`;box(`<div class="crumb"><button onclick="home()">Home</button> / ${esc(S.sub)} / ${esc(S.ch)}</div><section class="hero"><div class="eyebrow">${esc(S.sub.toUpperCase())}</div><h2>${esc(S.t)}</h2><span class="muted">Class ${S.c} • ${esc(S.b)}</span></section><div class="tabs">${['learn','practice','solve','quiz','formulas','ai'].map(x=>`<button class="${S.tab===x?'on':''}" onclick="S.tab='${x}';render()">${x==='ai'?'ASK AI':x.toUpperCase()}</button>`).join('')}</div>${body}`)}
function answer(i,j){let q=T().questions[i],f=document.getElementById('f'+i);f.innerHTML=j===q.answer?`<p class="correct"><b>Correct ✓</b> ${esc(q.explanation)}</p>`:`<p class="bad"><b>Not quite.</b> ${esc(q.explanation)}</p>`}
function solve(){let a=+aa.value,b=+bb.value,c=+cc.value,o=document.getElementById('sr');if(!Number.isFinite(a)||!Number.isFinite(b)||!Number.isFinite(c)){o.innerHTML='<p class="bad">Enter all three numbers.</p>';return}if(a===0){o.innerHTML=b===c?'<p class="result">Infinitely many solutions.</p>':'<p class="bad">No solution.</p>';return}let x=(c-b)/a;o.innerHTML=`<div class="content"><div class="result">x = ${x}</div><div class="formula">x = (c − b) / a = (${c} − ${b}) / ${a}</div></div>`}
function ask(){let q=document.getElementById('aq').value.trim(),o=document.getElementById('ar');if(!q){o.innerHTML='<p class="bad">Write a question first.</p>';return}if(S.used>=3){o.innerHTML='<p class="bad">Daily limit reached.</p>';return}S.used++;o.innerHTML=`<div class="content"><b>AI placeholder</b><p>The question was accepted. The real AI will be connected through a secure server so no API key is exposed in the browser.</p><p>${esc(q)}</p></div>`}
render();